using System;
using System.Windows.Forms;
using com.clearunit;
using SETUNA.Main.Runtime;

namespace SETUNA
{
    // Token: 0x02000086 RID: 134
    internal static class Program
    {
        // Token: 0x0600046B RID: 1131 RVA: 0x0001CA08 File Offset: 0x0001AC08
        [STAThread]
        private static void Main(string[] args)
        {
            // 必须在任何网络类型被触碰之前：单文件分发没有 app.config，TLS 开关
            // 只能由这里设置。
            RuntimeConfiguration.Apply();

            // Generated by the SDK project: EnableVisualStyles, then
            // SetCompatibleTextRenderingDefault(false), then
            // SetHighDpiMode(PerMonitorV2). It has to run before the first control
            // exists, not merely before the first form, because the middle call throws
            // InvalidOperationException once any window has been created. The DPI half
            // is a fallback that measurably does nothing here: app.manifest has already
            // made the process Per-Monitor V2 at creation time, so SetHighDpiMode
            // returns false. It matters only if the manifest ever loses its declaration.
            ApplicationConfiguration.Initialize();

            // Read back what the process actually reports. A manifest that lost its
            // dpiAwareness element leaves per-monitor layout off without any error.
            var dpiMismatch = RuntimeConfiguration.DescribeHighDpiModeMismatch();
            if (dpiMismatch != null)
            {
                Console.WriteLine(dpiMismatch);
            }

            // Before the singleton election on purpose: a self-test must never hand its
            // arguments to a SETUNA already in the tray, and must never take the mutex a
            // real launch is waiting for.
            if (args.Length > 0 && args[0] == SelfTest.Switch)
            {
                Environment.ExitCode = SelfTest.Run(args.Length > 1 ? args[1] : null);
                return;
            }

            var instance = SingletonApplication.GetInstance(Application.ProductVersion, args);
            if (instance.Register())
            {
                var mainform = new Mainform();
                instance.AddSingletonFormListener(mainform);
                mainform.CommandRun(args);
                Application.Run(mainform);
            }
        }
    }
}
